//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.10 at 05:11:43 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bsestarmf.in/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.BES.soap;
